import os
import shutil
import tempfile
import subprocess

import pytest

@pytest.fixture
def uds_dir():
    """A short-path temporary directory. AF_UNIX paths are capped at roughly
    104-108 bytes (struct sockaddr_un.sun_path), which pytest's own tmp_path
    routinely exceeds on macOS (/private/var/folders/.../pytest-of-.../...)."""

    with tempfile.TemporaryDirectory(dir="/tmp") as directory:
        yield directory

# The certificates are produced with the openssl command line tool so that the
# test material is generated by OpenSSL itself rather than by the code under
# test. The tool is looked up next to the library Kaede was pointed at, so both
# come from the same OpenSSL installation.

class Authority:
    """A throwaway CA and the certificates it issues, in a temporary directory."""

    def __init__(self, directory):
        self.directory = str(directory)
        self.openssl = Authority.locate()

        self.ca = self.path("ca.pem")
        self.ca_key = self.path("ca.key")

        self.build()

    @staticmethod
    def locate() -> str:
        library = os.environ.get("KAEDE_OPENSSL", "")

        if library:
            candidate = os.path.join(os.path.dirname(library.rstrip("/")), "bin", "openssl")

            if os.path.exists(candidate):
                return candidate

        return shutil.which("openssl") or "openssl"

    def path(self, name: str) -> str:
        return os.path.join(self.directory, name)

    def run(self, *arguments):
        result = subprocess.run([self.openssl, *arguments], capture_output=True)

        if result.returncode != 0:
            raise RuntimeError(
                f"{self.openssl} {' '.join(arguments)} failed with exit code {result.returncode}:\n"
                f"{result.stderr.decode(errors='replace')}"
            )

    def build(self):
        self.run(
            "req", "-x509", "-newkey", "rsa:2048", "-nodes",
            "-keyout", self.ca_key, "-out", self.ca,
            "-subj", "/CN=Kaede Test CA", "-days", "1",
            "-addext", "basicConstraints=critical,CA:TRUE",
            "-addext", "keyUsage=critical,keyCertSign,cRLSign",
            "-addext", "subjectKeyIdentifier=hash"
        )

    def issue(self, name: str, hosts: str, *, days: int = 1, expired: bool = False):
        """Issue a certificate signed by this CA. Returns (certfile, keyfile)."""

        key = self.path(f"{name}.key")
        csr = self.path(f"{name}.csr")
        certificate = self.path(f"{name}.pem")

        self.run("req", "-newkey", "rsa:2048", "-nodes", "-keyout", key, "-out", csr, "-subj", f"/CN={name}")

        extensions = self.path(f"{name}.ext")

        with open(extensions, "w") as f:
            f.write(
                f"subjectAltName={hosts}\nbasicConstraints=CA:FALSE\n"
                "subjectKeyIdentifier=hash\nauthorityKeyIdentifier=keyid:always,issuer\n"
            )

        validity = ["-not_before", "20200101000000Z", "-not_after", "20200102000000Z"] if expired else ["-days", str(days)]

        self.run(
            "x509", "-req", "-in", csr, "-CA", self.ca, "-CAkey", self.ca_key,
            "-CAcreateserial", "-out", certificate, "-extfile", extensions, *validity
        )

        return certificate, key

@pytest.fixture(scope="session")
def authority(tmp_path_factory):
    return Authority(tmp_path_factory.mktemp("pki"))

@pytest.fixture(scope="session")
def server_certificate(authority):
    return authority.issue("localhost", "DNS:localhost,IP:127.0.0.1")

@pytest.fixture(scope="session")
def other_certificate(authority):
    """A valid certificate for a name nobody in the tests connects to."""

    return authority.issue("elsewhere", "DNS:elsewhere.example")

@pytest.fixture(scope="session")
def expired_certificate(authority):
    return authority.issue("expired", "DNS:localhost,IP:127.0.0.1", expired=True)

class ECHKeys:
    """A real ECHConfig and its private key, generated by `openssl ech` (RFC 9849)."""

    def __init__(self, directory, public_name: str = "public.example"):
        self.openssl = Authority.locate()
        self.pemfile = os.path.join(str(directory), "ech.pem")
        self.public_name = public_name

        result = subprocess.run([self.openssl, "ech", "-public_name", public_name, "-out", self.pemfile], capture_output=True)

        if result.returncode != 0:
            raise RuntimeError(f"{self.openssl} ech failed with exit code {result.returncode}:\n{result.stderr.decode(errors='replace')}")

    @property
    def configlist(self) -> bytes:
        """The raw ECHConfigList bytes, as a client would receive them from a DNS HTTPS record."""

        import base64

        with open(self.pemfile) as f:
            pem = f.read()

        block = pem.split("-----BEGIN ECHCONFIG-----")[1].split("-----END ECHCONFIG-----")[0]
        return base64.b64decode(block)

@pytest.fixture(scope="session")
def ech_keys(tmp_path_factory):
    from kaede.tls.openssl import OpenSSL

    if OpenSSL().set_ech_config_list is None:
        pytest.skip("ECH needs OpenSSL 4.0 or newer")

    return ECHKeys(tmp_path_factory.mktemp("ech"))
