import importlib

import pytest

# Every module in the CLAUDE.md directory layout must be importable. Modules
# that are still unimplemented (the mail family) exist as empty files, and
# importing them must succeed all the same.
MODULES = [
    "kaede",
    "kaede.ip",
    "kaede.url",
    "kaede.models",
    "kaede.constants",
    "kaede.tls",
    "kaede.tls.models",
    "kaede.tls.errors",
    "kaede.tls.openssl",
    "kaede.tls.helpers",
    "kaede.tls.helpers.ech",
    "kaede.uds",
    "kaede.uds.models",
    "kaede.uds.errors",
    "kaede.uds.protocol",
    "kaede.uds.api.common",
    "kaede.uds.api.client",
    "kaede.uds.api.server",
    "kaede.tcp",
    "kaede.tcp.models",
    "kaede.tcp.errors",
    "kaede.tcp.protocol",
    "kaede.tcp.tls",
    "kaede.tcp.api.common",
    "kaede.tcp.api.client",
    "kaede.tcp.api.server",
    "kaede.udp",
    "kaede.udp.models",
    "kaede.udp.errors",
    "kaede.udp.protocol",
    "kaede.udp.tls",
    "kaede.udp.api.common",
    "kaede.udp.api.client",
    "kaede.udp.api.server",
    "kaede.quic",
    "kaede.quic.models",
    "kaede.quic.errors",
    "kaede.quic.tls",
    "kaede.quic.protocol",
    "kaede.quic.protocol.common",
    "kaede.quic.protocol.base",
    "kaede.quic.protocol.q1",
    "kaede.quic.protocol.q2",
    "kaede.quic.api.common",
    "kaede.quic.api.client",
    "kaede.quic.api.server",
    "kaede.dns",
    "kaede.dns.models",
    "kaede.dns.records",
    "kaede.dns.errors",
    "kaede.dns.protocol",
    "kaede.dns.protocol.handler",
    "kaede.dns.protocol.common",
    "kaede.dns.protocol.base",
    "kaede.dns.protocol.udp",
    "kaede.dns.protocol.tcp",
    "kaede.dns.protocol.tls",
    "kaede.dns.protocol.quic",
    "kaede.dns.protocol.https",
    "kaede.dns.api.common",
    "kaede.dns.api.client",
    "kaede.dns.api.server",
    "kaede.dns.helpers",
    "kaede.dns.helpers.dnssec",
    "kaede.http",
    "kaede.http.models",
    "kaede.http.headers",
    "kaede.http.errors",
    "kaede.http.responses",
    "kaede.http.finalizer",
    "kaede.http.websocket",
    "kaede.http.protocol",
    "kaede.http.protocol.handler",
    "kaede.http.protocol.common",
    "kaede.http.protocol.base",
    "kaede.http.protocol.h1",
    "kaede.http.protocol.h2",
    "kaede.http.protocol.h3",
    "kaede.http.helpers.dns",
    "kaede.http.helpers.hsts",
    "kaede.http.helpers.hpack",
    "kaede.http.helpers.qpack",
    "kaede.http.helpers.compression",
    "kaede.http.api.common",
    "kaede.http.api.client",
    "kaede.http.api.server",
    "kaede.mail",
    "kaede.mail.models",
    "kaede.mail.errors",
    "kaede.mail.helpers",
    "kaede.mail.helpers.dns",
    "kaede.mail.helpers.spf",
    "kaede.mail.helpers.dkim",
    "kaede.mail.helpers.dmarc",
    "kaede.smtp",
    "kaede.smtp.models",
    "kaede.smtp.errors",
    "kaede.smtp.tls",
    "kaede.smtp.protocol",
    "kaede.smtp.protocol.common",
    "kaede.smtp.protocol.base",
    "kaede.smtp.protocol.s1",
    "kaede.smtp.api.common",
    "kaede.smtp.api.client",
    "kaede.smtp.api.server",
    "kaede.imap",
    "kaede.imap.models",
    "kaede.imap.errors",
    "kaede.imap.tls",
    "kaede.imap.protocol",
    "kaede.imap.protocol.common",
    "kaede.imap.protocol.base",
    "kaede.imap.protocol.i1",
    "kaede.imap.protocol.i2",
    "kaede.imap.protocol.i3",
    "kaede.imap.protocol.i4",
    "kaede.imap.api.common",
    "kaede.imap.api.client",
    "kaede.imap.api.server",
    "kaede.pop",
    "kaede.pop.models",
    "kaede.pop.errors",
    "kaede.pop.tls",
    "kaede.pop.protocol",
    "kaede.pop.protocol.common",
    "kaede.pop.protocol.base",
    "kaede.pop.protocol.p1",
    "kaede.pop.protocol.p2",
    "kaede.pop.protocol.p3",
    "kaede.pop.api.common",
    "kaede.pop.api.client",
    "kaede.pop.api.server",
]

@pytest.mark.parametrize("name", MODULES)
def test_module_imports(name):
    importlib.import_module(name)

@pytest.mark.parametrize("name", MODULES)
def test_exports_resolve(name):
    module = importlib.import_module(name)

    for export in getattr(module, "__all__", []):
        assert hasattr(module, export), f"{name}.__all__ lists {export!r}, which does not exist"

def test_server_limits_are_not_shared_between_instances():
    from kaede.models import ServerLimits

    first, second = ServerLimits(), ServerLimits()
    first.max_connection_rate.append((3600, 1000))

    assert second.max_connection_rate != first.max_connection_rate
